@Base_url = http://localhost:3600
@Base_url_auth = http://localhost:3600/auth


### Home Route
GET {{Base_url}}
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiYWF6aW0iLCJpYXQiOjE2NzEwMTEyNTMsImV4cCI6MTY3MTAxMTU1MywiYXVkIjoiNjM5MmNlOTMyNjNiYjE5NjMyY2RhZTNkIiwiaXNzIjoiaGVscC5jb20ifQ.1Ypz8fmCy8QU2nR5v278S2OccRjNY2ONJlpdrC299Ic



###login route
POST {{Base_url_auth}}/login
Content-Type: application/json

{    
    "email":"emaill@gmail.com", 
    "password":"passss"
}

### register route
POST {{Base_url_auth}}/register
Content-Type: application/json

{    
    "email":"emaill@gmail.com",    
    "password":"passss"
}
### refresh toke route
POST {{Base_url_auth}}/refresh-token
Content-Type: application/json

{
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiYWF6aW0iLCJpYXQiOjE2NzEwMTQ3MDYsImV4cCI6MTY3MTAzMjcwNiwiYXVkIjoiNjM5MmNlOTMyNjNiYjE5NjMyY2RhZTNkIiwiaXNzIjoiaGVscC5jb20ifQ.yxqmCqybEfiBlV2a2duyvVEbZYjWUa-7QGijJOVk3ts"
    }



### logout route
DELETE {{Base_url_auth}}/logout
Content-Type: application/json

{
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiYWF6aW0iLCJpYXQiOjE2NzEwMTQ3MjMsImV4cCI6MTY3MTAzMjcyMywiYXVkIjoiNjM5MmNlOTMyNjNiYjE5NjMyY2RhZTNkIiwiaXNzIjoiaGVscC5jb20ifQ.P_5QBx424sSQ9Hzo4TZBrvCRCIdH9T82rnGBtB8e4Dw"
     }